services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secretpassword
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
#      interval: 5s
#      timeout: 3s
#      retries: 5
    restart: unless-stopped

volumes:
  clickhouse-data: