services:
  zookeeper-1:
    image: zookeeper:latest
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=*
    volumes:
      - zookeeper-1-data:/data
      - zookeeper-1-datalog:/datalog
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - clickhouse-net

  zookeeper-2:
    image: zookeeper:latest
    container_name: zookeeper-2
    ports:
      - "2182:2181"
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=*
    volumes:
      - zookeeper-2-data:/data
      - zookeeper-2-datalog:/datalog
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - clickhouse-net

  zookeeper-3:
    image: zookeeper:latest
    container_name: zookeeper-3
    ports:
      - "2183:2181"
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=*
    volumes:
      - zookeeper-3-data:/data
      - zookeeper-3-datalog:/datalog
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - clickhouse-net

  clickhouse-1:
    image: clickhouse/clickhouse-server:25.1
    container_name: clickhouse-1
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    volumes:
      - clickhouse-1-data:/var/lib/clickhouse
      - ./clickhouse-config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-config/config.d/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-config/users.d/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml      -
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secretpassword
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_LOGGER_LEVEL=trace  # Set log level to trace
      - CLICKHOUSE_LOGGER_CONSOLE=1    # Enable console logging
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
#    deploy:
#      resources:
#        limits:
#          memory: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - clickhouse-net

  clickhouse-2:
    image: clickhouse/clickhouse-server:25.1
    container_name: clickhouse-2
    ports:
      - "8124:8123"
      - "9001:9000"
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    volumes:
      - clickhouse-2-data:/var/lib/clickhouse
      - ./clickhouse-config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-config/config.d/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-config/users.d/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secretpassword
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
#    deploy:
#      resources:
#        limits:
#          memory: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - clickhouse-net

  clickhouse-3:
    image: clickhouse/clickhouse-server:25.1
    container_name: clickhouse-3
    ports:
      - "8125:8123"
      - "9002:9000"
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secretpassword
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-3-data:/var/lib/clickhouse
      - ./clickhouse-config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-config/config.d/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-config/users.d/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
#    deploy:
#      resources:
#        limits:
#          memory: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - clickhouse-net

volumes:
  zookeeper-1-data:
  zookeeper-1-datalog:
  zookeeper-2-data:
  zookeeper-2-datalog:
  zookeeper-3-data:
  zookeeper-3-datalog:
  clickhouse-1-data:
  clickhouse-2-data:
  clickhouse-3-data:

networks:
  clickhouse-net:
    driver: bridge